#! /bin/bash
#
# VERBOSE
# SKIP_ROOT

dotfiles_config="$HOME/.dotfiles-config"
touch $dotfiles_config

declare -a config_modules=()

# Load saved configuration and previously installed modules
if [[ -f "$dotfiles_config" ]]; then
  source "$dotfiles_config"
  # provides $config_modules
fi

echo '++++++++++++++++'
echo 'DOTFILES INSTALL'
echo '++++++++++++++++'

if [[ -n $SKIP_ROOT ]]; then
  echo "Will skip root commands..."
  echo ""
fi

source_file="$HOME/.dotfiles-source"
source_command="source $source_file"

# Ensure ~/.dotfiles-source is called from ~/.bashrc
if ! grep -Fxq "$source_command" "$HOME/.bashrc"; then
  echo "$source_command" >> "$HOME/.bashrc"
fi

# Reset intermediate dynamic source file
cat <<'SOURCE' > $source_file
# THIS FILE IS GENERATED BY dotfiles-install.sh
# ---
# DO NOT TRACK IN GIT
# ---
# DO NOT MANUALLY EDIT
#

SOURCE

declare -A root_commands

# Buffer commands requiring elevated privileges per module
as_root() {
  if [[ -z $SKIP_ROOT ]]; then
    module=$(basename $(dirname "${BASH_SOURCE[1]}"))

    code=$1
    if [ -z "$code" ]; then
      read code
    fi

    root_commands[$module]=$(printf '%q' "$code")

    echo "  > Added commands to run as root"
  fi
}

modules_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.dotfiles-modules"

# Discover available modules on disk
valid_modules=( $modules_root/*/ )
valid_modules=( "${valid_modules[@]%/}" )
valid_modules=( "${valid_modules[@]#"$modules_root/"}" )

requested_modules=($@)

# Validate requested module names against disk
declare -A in_VALID_MODULES=(); for x in "${valid_modules[@]}"; do in_VALID_MODULES["$x"]=1; done
declare -A found=(); invalid=()
for x in "${requested_modules[@]}"; do
  if [[ -z ${in_VALID_MODULES[$x]+_} && -z ${found[$x]+_} ]]; then
    found["$x"]=1
    invalid+=("$x")
  fi
done

if (( ${#invalid[@]} > 0 )); then
    echo ''
    echo 'Invalid modules requested'
    printf "  %s\n"  "${invalid[@]}"
    exit 0
fi

# Fallback to all discovered modules if no modules requested or saved
if (( ${#requested_modules[@]} == 0 && ${#config_modules[@]} == 0)); then
  echo "Using all modules"
  requested_modules=( "${valid_modules[@]}" )
fi

# Append saved modules from configuration
if (( ${#config_modules[@]} != 0)); then
  if (( ${#requested_modules[@]} == 0 )); then
    echo "Using modules from config"
  else
    echo "Adding requested modules to config"
  fi

  requested_modules+=("${config_modules[@]}")
fi

# Set base default modules
modules=('base')

# Merge requested modules and keep unique entries
modules+=("${requested_modules[@]}")
mapfile -t modules < <(printf '%s\n' "${modules[@]}" | sort -u)

echo "[ ${modules[@]} ]"

modules_count=${#modules[@]}
index=0

# Iterate over each module to register sources and execute user install logic
for module in "${modules[@]}"; do
  ((index++))

  echo ''
  echo "( $index / $modules_count ) Processing [$module]"

  module_directory="$modules_root/$module"

  # Register module source hook
  module_source_file="$module_directory/source.sh"
  if [[ -f "$module_source_file" ]]; then
    module_source_command="source $module_source_file"

    if ! grep -Fxq "$module_source_command" "$source_file"; then
      echo "  Applying source"
      echo "$module_source_command" >> "$source_file"
    fi
  fi

  # Execute non-root installation steps
  module_install_file="$module_directory/install.sh"
  if [[ -f "$module_install_file" ]]; then
    echo "  Running install"
    source "$module_install_file"
  fi
done

# Prepare the batch payload for elevated execution
read -r -d '' root_needed <<'_'
  eval "$param"

  root_modules_count=${#root_commands[@]}
  root_index=0

  # Package manager refresh prioritizing DNF over APT
  if command -v dnf &>/dev/null; then
    dnf check-update || true
  elif command -v apt-get &>/dev/null; then
    apt-get update &>>"$VERBOSE_OUTPUT"
    apt-get upgrade -y &>>"$VERBOSE_OUTPUT"
  fi

  for module in $(printf "%s\n" "${!root_commands[@]}" | LC_ALL=C sort); do
    ((root_index++))

    echo ''
    echo "( $root_index / $root_modules_count ) Running as root [$module]"

    eval "code=${root_commands[$module]}"

    # Inject non-interactive flags based on package manager
    if command -v dnf &>/dev/null; then
      code="${code//dnf /dnf -y }"
    elif command -v apt-get &>/dev/null; then
      code="${code//apt /apt -y }"
      code="${code//apt-get/apt-get -y}"
      export DEBIAN_FRONTEND=noninteractive
    fi

    eval "$code" &>>"$VERBOSE_OUTPUT"
  done
_

# Execute buffered root tasks in a single elevated session
if [[ -z $SKIP_ROOT && ${#root_commands[@]} -gt 0 ]]; then
  echo ''
  echo 'Root needed for further configuration'

  output="${VERBOSE:-'/dev/null'}"

  # Fallback to sudo if su -lc fails or passwordless sudo is configured
  if command -v sudo &>/dev/null; then
    sudo bash -c "VERBOSE_OUTPUT=\"$output\"; param='$(declare -p root_commands)'; eval '$root_needed'"
  else
    su -lc "VERBOSE_OUTPUT=\"$output\"; param='$(declare -p root_commands)'; eval '$root_needed'"
  fi
fi

# First time system sanity checks and Git identity
if (( ${#config_modules[@]} == 0 )); then
  if [[ -z "$(git config --global user.email)" ]]; then
    echo ''
    echo 'Git config'
    echo 'git config --global user.email <email>'
    echo 'git config --global user.name <name>'
  fi

  if ! [[ -f "$HOME/.ssh/id_ed25519" || -f "$HOME/.ssh/id_rsa" ]]; then
    echo ''
    echo 'SSH Key (Ed25519)'
    ssh-keygen -t ed25519 -f "$HOME/.ssh/id_ed25519" -P ""
    eval "$(ssh-agent -s)"
    ssh-add "$HOME/.ssh/id_ed25519"
  fi
fi

# Persist active configuration to disk
config_modules=( "${modules[@]}" )
config_modules_declare="$(declare -p config_modules)"

if grep -Fq "config_modules" "$dotfiles_config"; then
  sed -i "/config_modules/s/^.*$/$config_modules_declare/" "$dotfiles_config"
else
  echo "$config_modules_declare" >> "$dotfiles_config"
fi

source "$HOME/.bashrc"

echo ''
echo '~~~~'
echo 'DONE'
echo '~~~~'